name: update
on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:
jobs:
  update-podcasts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install -r requirements.txt
      - run: python3 rijkspodcast.py update
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: 'Update podcasts'
          file_pattern: 'podcasts.json'
